#!/bin/bash
# Initialize osis doc structure for a project
# Usage: bash init.sh [product-version]
# Example: bash init.sh mystory-v3

set -e

VERSION="${1:-product-v1}"
BASE="osis/${VERSION}"

if [ -d "osis" ] && [ -d "$BASE" ]; then
  echo "Directory $BASE already exists. Aborting."
  exit 1
fi

mkdir -p "$BASE"
mkdir -p "$BASE/archive"

# Create osis.json
cat > "osis/osis.json" << EOF
{
  "version": "1.0",
  "product": null,
  "productVersion": "${VERSION}",
  "activePhase": null,
  "lastTwinUpdate": null,
  "lastDriftScan": null
}
EOF

# Create README at osis root
cat > "osis/README.md" << 'EOF'
# Product Documentation

This folder contains the product specs for this project, managed by the [osis protocol](https://osis.dev).

Osis is a product clarity system. It maintains two things:

- **`twin.md`** — what the product IS. Code compressed into natural language so agents and humans understand faster.
- **`{version}/`** — what the product is BECOMING. Structured specs that define the future.

## For AI Agents

Before starting work on any product feature, read in this order:

1. `osis.json` — understand the current state
2. `twin.md` — understand the product as it exists today
3. Active phase `game-plan.md` — understand what's in scope
4. Relevant `{system}--product-spec.md` — understand intended behavior
5. Relevant `{system}--implementation-spec.md` — understand how to build it

If a spec doesn't exist yet, flag it before proceeding.

Learn more at [osis.dev](https://osis.dev).
EOF

# Create twin placeholder
cat > "osis/twin.md" << 'EOF'
# Digital Twin

<!-- Generated by osis. Run osis twin update to refresh. -->
EOF

# Create canon placeholders
cat > "$BASE/vision.md" << 'EOF'
# [Project Name]

## [Subtitle]

*A Manifesto*

---

*[Organization] — [Date]*

---

<!-- Run osis bootstrap to build this with guidance -->
EOF

cat > "$BASE/product-spec.md" << 'EOF'
# [Project Name] — Product Spec

Last updated: [Date]

---

<!-- Run osis bootstrap to build this with guidance -->
EOF

# Create changelog
cat > "$BASE/changelog.md" << 'EOF'
# Changelog
EOF

echo ""
echo "Created osis doc structure:"
echo ""
echo "  osis/"
echo "    osis.json"
echo "    README.md"
echo "    twin.md"
echo "    $VERSION/"
echo "      vision.md"
echo "      product-spec.md"
echo "      changelog.md"
echo "      archive/"
echo ""
echo "Next steps:"
echo "  1. Run 'osis bootstrap' to build your product docs"
echo "  2. Add product doc pointers to your CLAUDE.md or agent config"
